# -*- coding: utf-8 -*-
"""SHOW TODOMUNDONORIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pSyaIkTAfGxkCZvJCRqRgfqzaSL5BDnO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Preparação dos Dados (Dados Reais Históricos RJ)
data = {
    'Artista': ['Madonna', 'Lady Gaga', 'Shakira'],
    'Ano': [2024, 2025, 2026],
    'Publico_Milhoes': [1.6, 2.1, 2.0], # Shakira estabilizou o público de massa
    'Policiamento_Agentes': [3200, 7475, 7927], # Aumento significativo na segurança
    'Ocorrencias': [213, 238, 115] # Eficiência da segurança aumentou (queda em 2026)
}

df = pd.DataFrame(data)

# 2. Cálculo de Projeção para 2027 (Média de crescimento/tendência)
# Projeção simples baseada na média de público e necessidade logística
prox_publico = df['Publico_Milhoes'].mean() * 1.05  # Expectativa de leve alta
prox_policiamento = df['Policiamento_Agentes'].max() * 1.10 # Margem de segurança maior

# 3. Configuração Visual do Dashboard
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(15, 12))
fig.suptitle('Dashboard: Megashows em Copacabana (Comparativo e Projeção 2027)', fontsize=20, fontweight='bold')

# Gráfico 1: Público Total
sns.barplot(ax=axes[0, 0], x='Artista', y='Publico_Milhoes', data=df, palette='magma')
axes[0, 0].set_title('Público Estimado (em milhões)', fontsize=14)
axes[0, 0].set_ylabel('Milhões de Pessoas')

# Gráfico 2: Efetivo Policial (Progressão)
sns.lineplot(ax=axes[0, 1], x='Ano', y='Policiamento_Agentes', data=df, marker='o', color='blue', linewidth=3)
axes[0, 1].set_title('Evolução do Efetivo de Segurança (Agentes)', fontsize=14)
axes[0, 1].set_xticks([2024, 2025, 2026])

# Gráfico 3: Eficiência (Ocorrências vs Policiamento)
sns.scatterplot(ax=axes[1, 0], x='Policiamento_Agentes', y='Ocorrencias', size='Publico_Milhoes',
                hue='Artista', data=df, sizes=(100, 500), palette='viridis')
axes[1, 0].set_title('Correlação: Policiamento vs Ocorrências', fontsize=14)

# Gráfico 4: Projeção 2027
proj_data = pd.DataFrame({
    'Categoria': ['Público (M)', 'Policiamento (Agentes/10)'],
    'Valores': [prox_publico, prox_policiamento/10] # Escala ajustada para o gráfico
})
sns.barplot(ax=axes[1, 1], x='Categoria', y='Valores', data=proj_data, palette='rocket')
axes[1, 1].set_title('Projeção para o Show de 2027', fontsize=14)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# Exibição dos Insights
print(f"--- INSIGHTS PARA O ANO QUE VEM (2027) ---")
print(f"1. Público Estimado: {prox_publico:.2f} milhões de pessoas.")
print(f"2. Necessidade de Policiamento: {int(prox_policiamento)} agentes.")
print(f"3. Tendência: O uso de tecnologia (reconhecimento facial) reduziu as ocorrências no show da Shakira em 50% "
      f"mesmo com público recorde. Para 2027, o foco deve ser em contenção de fluxo e não apenas repressão.")